name: Login Regression Tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Allows manual trigger

jobs:
  login-tests:
    name: Run Login Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run login regression tests
        run: npx playwright test --config=tests/suites/login.suite.js --reporter=html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/index.html
          retention-days: 30

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: 'test-results/login-junit-results.xml'
          check_name: 'Login Test Results'
          fail_on_failure: true 